name: rmsd_snek
channels:
  - bioconda
  - anaconda
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amply=0.1.5=pyhd8ed1ab_0
  - apbs=1.5=h14c3975_3
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=openblas
  - boto3=1.26.138=pyhd8ed1ab_0
  - botocore=1.29.138=pyhd8ed1ab_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - curl=7.88.1=h5eee18b_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.20.1=py38h578d9bd_0
  - dpath=2.1.6=pyha770c72_0
  - dropbox=11.36.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.4.9=h6a678d5_0
  - filechunkio=1.8=py_2
  - filelock=3.12.0=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freemol=1.158=py_2
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - ftputil=5.0.4=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glew=2.0.0=0
  - glib=2.69.1=he621ea3_2
  - google-api-core=2.8.2=pyhd8ed1ab_0
  - google-api-python-client=2.86.0=pyhd8ed1ab_0
  - google-auth=2.18.1=pyh1a96a4e_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.9.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py38h57c428a_3
  - google-resumable-media=2.5.0=pyhd8ed1ab_0
  - grpcio=1.42.0=py38hce63b2e_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - hdf5=1.10.6=hb1b8bf9_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py38h578d9bd_4
  - icu=58.2=he6710b0_3
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py38h578d9bd_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h6e990d7_netlib
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.17=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libglu=9.0.0=hf484d3e_1
  - libgomp=11.2.0=h1234567_1
  - libholoplaycore=0.1.0_rc4=1
  - libllvm10=10.0.1=hbcb73fb_5
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.18=hf726d26_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.15.8=h780b84a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=h8f2d780_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - logmuse=0.2.6=pyh8c360ce_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - matplotlib-base=3.7.1=py38h417a72b_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mengine=1=h14c3975_1
  - mkl=2023.1.0=h6d00ec8_46342
  - mpeg_encode=1=h14c3975_1
  - mtz2ccp4_px=1.0=h9ac9557_3
  - multidict=6.0.2=py38h5eee18b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.1=py38hecfb737_0
  - numpy=1.22.3=py38h7a5d4dd_0
  - numpy-base=1.22.3=py38hb8be1f0_0
  - oauth2client=4.1.3=py_0
  - openssl=1.1.1u=h7f8727e_0
  - packaging=23.0=py38h06a4308_0
  - pandas=1.5.3=py38h417a72b_0
  - paramiko=3.1.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pdb2pqr=2.1.2+pymol=py_0
  - peppy=0.35.5=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plac=1.3.5=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py38_0
  - pmw=2.0.1+3=py_3
  - prettytable=3.7.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=3.15.8=py38h709712a_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py38h578d9bd_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py38h0a891b7_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=7.3.1=pyhd8ed1ab_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-irodsclient=1.1.8=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.3.5=pyhd8ed1ab_0
  - rigimol=1.3=2
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.1=pyhd8ed1ab_0
  - scipy=1.7.3=py38h492baa0_0
  - seaborn=0.12.2=py38h06a4308_0
  - setuptools=66.0.0=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.3.0=pyhd8ed1ab_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.25.0=hdfd78af_0
  - snakemake-minimal=7.25.0=pyhdfd78af_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - throttler=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.0=hd8ed1ab_0
  - typing_extensions=4.6.0=pyha770c72_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.15=py38h06a4308_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yte=1.5.1=pyha770c72_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - pdbecif==1.5
    - libgfortran4==7.5.0=ha8ba4b0_17
    - libnetcdf==4.8.1=h8322cc2_2
    - libstdcxx-ng==11.2.0=h1234567_1
    - h5py==3.7.0=py38h737f45e_0
    - python==3.8.16=h7a1cb2a_3
    - bcrypt==3.2.2=py38h0a891b7_0
    - libxkbcommon==1.0.1=hfa300c1_0
    - qt-main==5.15.2=h327a75a_7
    - libedit==3.1.20221030=h5eee18b_0
    - ca-certificates==2023.5.7=hbcca054_0
    - wheel==0.38.4=py38h06a4308_0
    - fontconfig==2.14.1=h52c9d5c_1
    - mkl-service==2.4.0=py38h5eee18b_1
    - yarl==1.7.2=py38h0a891b7_2
    - jpeg==9e=h5eee18b_1
    - pyzmq==19.0.2=py38ha71036d_2
    - datrie==0.8.2=py38h497a2fe_3
    - krb5==1.19.4=h568e23c_0
    - pymol==2.4.1=py38h4463551_0
    - libtiff==4.5.0=h6a678d5_2
    - qt-webengine==5.15.9=hd2b0992_4
    - googleapis-common-protos==1.57.0=py38h578d9bd_0
    - libxcb==1.15=h7f8727e_0
    - idna==3.4=py38h06a4308_0
    - liblapack==3.9.0=3_h893e4fe_netlib
    - hdf4==4.2.13=h3ca952b_2
    - brotli-bin==1.0.9=h166bdaf_7
    - pyrsistent==0.18.0=py38heee7806_0
    - coincbc==2.10.5=hab63836_1
    - requests==2.29.0=py38h06a4308_0
    - markupsafe==2.1.1=py38h7f8727e_0
    - pyopenssl==23.0.0=py38h06a4308_0
    - lz4-c==1.9.4=h6a678d5_0
    - libcurl==7.88.1=h91b91d3_0
    - biopython==1.78=py38h7f8727e_0
    - intel-openmp==2023.1.0=hdb19cb5_46305
    - _openmp_mutex==5.1=1_gnu
    - libcrc32c==1.1.2=h9c3ff4c_0
    - libuuid==1.41.5=h5eee18b_0
    - matplotlib==3.7.1=py38h578d9bd_0
    - libzip==1.8.0=h5cef20c_0
    - c-ares==1.19.0=h5eee18b_0
    - libbrotlicommon==1.0.9=h166bdaf_7
    - libcblas==3.9.0=3_h893e4fe_netlib
    - libprotobuf==3.15.8=h780b84a_1
    - icu==58.2=he6710b0_3
    - gstreamer==1.14.1=h5eee18b_1
    - libdeflate==1.17=h5eee18b_0
    - libopenblas==0.3.18=hf726d26_0
    - tornado==6.1=py38h0a891b7_3
    - aiohttp==3.8.1=py38h0a891b7_1
    - lerc==3.0=h295c915_0
    - libwebp-base==1.2.4=h5eee18b_1
    - aioeasywebdav==2.4.0=py38h578d9bd_1001
    - freetype==2.12.1=h4a9f257_0
    - brotli==1.0.9=h166bdaf_7
    - google-crc32c==1.1.2=py38h57c428a_3
    - grpcio==1.42.0=py38hce63b2e_0
    - apbs==1.5=h14c3975_3
    - libllvm10==10.0.1=hbcb73fb_5
    - seaborn==0.12.2=py38h06a4308_0
    - libnghttp2==1.46.0=hce63b2e_0
    - debugpy==1.5.1=py38h295c915_0
    - xz==5.4.2=h5eee18b_0
    - docutils==0.20.1=py38h578d9bd_0
    - humanfriendly==10.0=py38h578d9bd_4
    - readline==8.2=h5eee18b_0
    - jupyter_core==5.3.0=py38h578d9bd_0
    - libclang==10.0.1=default_hb85057a_2
    - tbb==2021.8.0=hdb19cb5_0
    - contourpy==1.0.5=py38hdb19cb5_0
    - libbrotlienc==1.0.9=h166bdaf_7
    - zeromq==4.3.4=h9c3ff4c_1
    - libssh2==1.10.0=h8f2d780_0
    - kiwisolver==1.4.4=py38h6a678d5_0
    - glib==2.69.1=he621ea3_2
    - ld_impl_linux-64==2.38=h1181459_1
    - frozenlist==1.3.3=py38h5eee18b_0
    - libffi==3.4.4=h6a678d5_0
    - libholoplaycore==0.1.0_rc4=1
    - protobuf==3.15.8=py38h709712a_0
    - sqlite==3.41.2=h5eee18b_0
    - libpng==1.6.39=h5eee18b_0
    - libbrotlidec==1.0.9=h166bdaf_7
    - libwebp==1.2.4=h11a3e52_1
    - brotlipy==0.7.0=py38h27cfd23_1003
    - mkl==2023.1.0=h6d00ec8_46342
    - libev==4.33=h7f8727e_1
    - gst-plugins-base==1.14.1=h6a678d5_1
    - bzip2==1.0.8=h7b6447c_0
    - cffi==1.15.1=py38h5eee18b_3
    - libevent==2.1.12=h8f2d780_0
    - nspr==4.33=h295c915_0
    - zstd==1.5.5=hc292b87_0
    - lcms2==2.12=h3be6417_0
    - matplotlib-base==3.7.1=py38h417a72b_1
    - libblas==3.9.0=1_h6e990d7_netlib
    - dbus==1.13.18=hb2f20db_0
    - packaging==23.0=py38h06a4308_0
    - openssl==1.1.1u=h7f8727e_0
    - scipy==1.7.3=py38h492baa0_0
    - libgcc-ng==11.2.0=h1234567_1
    - qtwebkit==5.212=h4eab89a_4
    - zlib==1.2.13=h5eee18b_0
    - pillow==9.4.0=py38h6a678d5_0
    - multidict==6.0.2=py38h5eee18b_0
    - numpy==1.22.3=py38h7a5d4dd_0
    - mtz2ccp4_px==1.0=h9ac9557_3
    - libxml2==2.9.14=h74e7548_0
    - nss==3.74=h0370c37_0
    - pandas==1.5.3=py38h417a72b_0
    - pyyaml==6.0=py38h0a891b7_4
    - pysocks==1.7.1=py38h06a4308_0
    - expat==2.4.9=h6a678d5_0
    - cryptography==39.0.1=py38h9ce1e76_0
    - pyqt5-sip==12.11.0=py38h6a678d5_1
    - libsodium==1.0.18=h36c2ea0_1
    - ncurses==6.4=h6a678d5_0
    - pynacl==1.5.0=py38h0a891b7_1
    - curl==7.88.1=h5eee18b_0
    - libgomp==11.2.0=h1234567_1
    - libpq==12.9=h16c4e8d_3
    - libglu==9.0.0=hf484d3e_1
    - mpeg_encode==1=h14c3975_1
    - hdf5==1.10.6=hb1b8bf9_0
    - pulp==2.7.0=py38h578d9bd_0
    - yaml==0.2.5=h7f98852_2
    - tk==8.6.12=h1ccaba5_0
    - pip==23.0.1=py38h06a4308_0
    - giflib==5.2.1=h5eee18b_3
    - mengine==1=h14c3975_1
    - numexpr==2.8.1=py38hecfb737_0
    - pyqt==5.15.7=py38h6a678d5_1
    - psutil==5.9.0=py38h5eee18b_0
    - urllib3==1.26.15=py38h06a4308_0
    - libgfortran-ng==7.5.0=ha8ba4b0_17
    - bottleneck==1.3.5=py38h7deecbd_0
    - pcre==8.45=h295c915_0
    - numpy-base==1.22.3=py38hb8be1f0_0
    - sip==6.6.2=py38h6a678d5_0
    - wrapt==1.12.1=py38h497a2fe_3
    - libxslt==1.1.35=h4e12654_0
prefix: /home/bjechow/anaconda3/envs/rmsd_snek
